name: larosa_block
description: "A new Flutter project."
publish_to: 'none'
version: 2.44.2+61

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  video_thumbnail: ^0.5.3
  go_router: ^14.2.8
  provider: ^6.1.2
  modal_bottom_sheet: ^3.0.0
  http: ^1.2.2
  flutter_animate: ^4.5.0
  carousel_slider: ^5.0.0
  just_audio: ^0.9.39
  geocoding: ^3.0.0
  camera: ^0.11.0+2
  record: ^5.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  cached_network_image: ^3.3.1
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  hive: ^2.2.3
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.9.0
  flutter_typeahead: ^5.2.0
  permission_handler: ^11.3.1
  like_button: ^2.0.5
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  flutter_emoji: ^2.5.1
  flutter_polyline_points: ^2.1.0
  flutter_hooks: ^0.20.5
  dio: ^5.4.2+1
  http_parser: ^4.0.2
  video_player: ^2.9.3
  lottie: ^3.1.3
  visibility_detector: ^0.4.0+2
  audioplayers: ^6.1.0
  mime: ^1.0.5
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  stomp_dart_client: ^2.0.0
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.1
  equatable: ^2.0.5
  timeago: ^3.7.0
  flutter_dotenv: ^5.1.0
  cached_video_player_plus: ^3.0.3
  logger: ^2.4.0
  connectivity_plus: ^6.0.5
  another_flutter_splash_screen: ^1.2.1
  flutter_content_placeholder: ^0.0.3
  hugeicons: ^0.0.7
  awesome_snackbar_content: ^0.1.4
  toastification: ^2.3.0
  file_picker: ^8.0.7
  crop_your_image: ^1.1.0
  ionicons: ^0.2.2
  web_socket_channel: ^2.4.3
  multi_select_flutter: ^4.1.3
  photo_view: ^0.15.0
  flutter_sound: ^9.27.0
  avatar_glow: ^3.0.1
  flutter_local_notifications: ^17.2.4
  recase: ^4.1.0
  animated_text_kit: ^4.2.2
  image_cropper: ^9.0.0
  google_sign_in: ^6.2.2
  sqflite: ^2.4.1
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.1.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_icons/
    - assets/gifs/
    - assets/lotties/
    - .env

  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
